baseurl = "http://eikedawid.github.io/"
languageCode = "en-gb"
canonifyurls = true
title = "Your site title"
# Copyright notice. This is displayer in the footer.
copyright = "&copy; Copyright notice"

[params]
    # Social accounts. Link to these accounts are displayed in the header and
    # footer.
    twitter = "Your Twitter username"
    github = "Your GitHub username"
    linkedin = "Your LinkedIn username"
    googleplus = "Your Google+ user id"
    facebook = ""
    stackoverflow = "Your Stackoverflow user id (number)"
    keybase = "Your keybase.io username"
    # Google Analytics API key.
    # ga_api_key = "Your Google Analytics tracking id"
    # Mixpanel API key.
    # mixpanel_api_key = "Your Mixpanel API key"
    author = "Eike Dawid"
    avatar = "/path/to/avatar"
    contact = "Your contact link (ex. mailto:foo@example.com)"
    bio = "Your short bio/tagline"
    # Short subtitle/tagline. This is displayed in the header.
    subtitle = "is a software developer."
    # themecolor = "#hexcolor" # Defines the tab color in Chrome for Android.
